dist: focal

language: python
python:
  - 3.7
  - 3.8
  - 3.9

addons:
  apt:
    packages:
      - gdal-bin
      - libgdal-dev

install:
  - pip install --upgrade pip
  - CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal pip install 'gdal==3.0.4'
  - pip install codecov coverage isort flake8 twine black
  - pip install -e .

script:
 - black --check .
 - flake8 --max-line-length=88 .
 - isort --recursive --check-only --diff evaporation tests
 - ./setup.py sdist bdist_wheel
 - twine check dist/*
 - coverage run --include="./*" --omit="docs/","*/tests/*","*/tests.py","setup.py" -m unittest -v

after_success:
  - codecov
